const Data = [
    {
      id:1,
      img: "https://res.cloudinary.com/diogyja1g/image/upload/v1693222323/1_rt59oi.jpg",
      disc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe sit illum mollitia sunt numquam officia odit molestiae fugiat dicta voluptas!",
      role: "Aron Hunde",
    },
    { id:2,
      img: "https://res.cloudinary.com/diogyja1g/image/upload/v1693222355/9_v0if8x.jpg",
      disc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe sit illum mollitia sunt numquam officia odit molestiae fugiat dicta voluptas!",
      role: "Aron Hunde",
    },
    { id:3,
      img: "https://res.cloudinary.com/diogyja1g/image/upload/v1693222352/4_ixvcfu.jpg",
      disc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe sit illum mollitia sunt numquam officia odit molestiae fugiat dicta voluptas!",
      role: "Aron Hunde",
    },
    { id:4,
      img: "https://res.cloudinary.com/diogyja1g/image/upload/v1693222354/5_jl5qia.jpg",
      disc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe sit illum mollitia sunt numquam officia odit molestiae fugiat dicta voluptas!",
      role: "Aron Hunde",
    },
    { id:5,
      img: "https://res.cloudinary.com/diogyja1g/image/upload/v1693222350/2_i8yqkw.jpg",
      disc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe sit illum mollitia sunt numquam officia odit molestiae fugiat dicta voluptas!",
      role: "Aron Hunde",
    },
    {id:6,
      img: "https://res.cloudinary.com/diogyja1g/image/upload/v1693222349/3_bonsem.jpg",
      disc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe sit illum mollitia sunt numquam officia odit molestiae fugiat dicta voluptas!",
      role: "Aron Hunde",
    },
    {id:7,
      img: "https://res.cloudinary.com/diogyja1g/image/upload/v1693222352/6_snnlil.jpg",
      disc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe sit illum mollitia sunt numquam officia odit molestiae fugiat dicta voluptas!",
      role: "Aron Hunde",
    },
    {id:8,
      img: "https://res.cloudinary.com/diogyja1g/image/upload/v1693222352/7_o23tp6.jpg",
      disc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe sit illum mollitia sunt numquam officia odit molestiae fugiat dicta voluptas!",
      role: "Aron Hunde",
    },
    { id:9,
      img: "https://res.cloudinary.com/diogyja1g/image/upload/v1693222352/8_jri9po.jpg",
      disc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe sit illum mollitia sunt numquam officia odit molestiae fugiat dicta voluptas!",
      role: "Aron Hunde",
    },
  ];

 
  export default  Data